-- Particle System Configuration
-- Generated by Particle System Editor

local particleConfig = {
    maxParticles = 926,
    emissionRate = 98.3,
    blendMode = 0,  -- Additive

    -- Emission polygon (4 vertices)
    emissionVertices = {-5.000, -5.000, 5.000, -5.000, 5.000, 5.000, -5.000, 5.000},
    emissionVertexCount = 4,

    -- Velocity
    velocityMinX = -0.05,
    velocityMaxX = 0.05,
    velocityMinY = 0.05,
    velocityMaxY = 0.05,

    radialVelocityMin = 0.00,
    radialVelocityMax = 0.00,

    -- Acceleration
    accelerationMinX = 0.00,
    accelerationMaxX = 0.00,
    accelerationMinY = 0.05,
    accelerationMaxY = -0.05,

    radialAccelerationMin = 0.00,
    radialAccelerationMax = 0.00,

    -- Size
    startSizeMin = 0.025,
    startSizeMax = 0.050,
    endSizeMin = 0.010,
    endSizeMax = 0.005,

    -- Start color
    colorMinR = 0.979, colorMaxR = 1.000,
    colorMinG = 1.000, colorMaxG = 1.000,
    colorMinB = 0.839, colorMaxB = 0.618,
    colorMinA = 0.212, colorMaxA = 1.000,

    -- End color
    endColorMinR = 0.912, endColorMaxR = 0.971,
    endColorMinG = 1.000, endColorMaxG = 1.000,
    endColorMinB = 0.000, endColorMaxB = 0.000,
    endColorMinA = 0.000, endColorMaxA = 0.000,

    -- Lifetime
    lifetimeMin = 0.25,
    lifetimeMax = 2.00,

    -- Rotation
    rotationMinX = 0.00, rotationMaxX = 0.00,
    rotationMinY = 0.00, rotationMaxY = 0.00,
    rotationMinZ = 0.00, rotationMaxZ = 6.28,
    rotVelocityMinX = 0.00, rotVelocityMaxX = 0.00,
    rotVelocityMinY = 0.00, rotVelocityMaxY = 0.00,
    rotVelocityMinZ = -1.00, rotVelocityMaxZ = 1.00,

    -- Textures (stored as names for editor)
    textureNames = {"res/fx/hardness_75.png"}
}

return particleConfig
