-- Particle System Configuration
-- Generated by Particle System Editor

local particleConfig = {
    maxParticles = 1160,
    emissionRate = 54.3,
    blendMode = 0,  -- PARTICLE_BLEND_ADDITIVE

    -- Point emitter (no polygon)
    emissionVertices = {0.0, 0.0},
    emissionVertexCount = 0,

    -- Velocity
    velocityMinX = 0.00,
    velocityMaxX = 0.00,
    velocityMinY = 0.10,
    velocityMaxY = 0.50,

    radialVelocityMin = 0.00,
    radialVelocityMax = 0.00,

    -- Acceleration
    accelerationMinX = 0.00,
    accelerationMaxX = 0.00,
    accelerationMinY = 0.00,
    accelerationMaxY = 0.00,

    radialAccelerationMin = 0.00,
    radialAccelerationMax = 0.00,

    -- Size
    startSizeMin = 0.055,
    startSizeMax = 1.175,
    endSizeMin = 0.015,
    endSizeMax = 0.053,

    -- Start color
    colorMinR = 1.000, colorMaxR = 1.000,
    colorMinG = 0.800, colorMaxG = 1.000,
    colorMinB = 0.000, colorMaxB = 0.300,
    colorMinA = 1.000, colorMaxA = 1.000,

    -- End color
    endColorMinR = 1.000, endColorMaxR = 1.000,
    endColorMinG = 0.000, endColorMaxG = 0.200,
    endColorMinB = 0.000, endColorMaxB = 0.000,
    endColorMinA = 0.000, endColorMaxA = 0.000,

    -- Lifetime
    lifetimeMin = 0.26,
    lifetimeMax = 0.37,

    -- Textures (stored as names for editor)
    textureNames = {"res/fx/bloom.png"}
}

return particleConfig
