-- Particle System Configuration
-- Generated by Particle System Editor

local particleConfig = {
    maxParticles = 508,
    emissionRate = 496.4,
    blendMode = 1,  -- Alpha

    -- Emission polygon (2 vertices)
    emissionVertices = {0.020, 0.000, -0.020, 0.000},
    emissionVertexCount = 2,

    -- Velocity
    velocityMinX = -0.14,
    velocityMaxX = 0.12,
    velocityMinY = 0.09,
    velocityMaxY = 0.35,

    radialVelocityMin = 0.00,
    radialVelocityMax = 0.00,

    -- Acceleration
    accelerationMinX = 0.00,
    accelerationMaxX = 0.00,
    accelerationMinY = 0.00,
    accelerationMaxY = 0.12,

    radialAccelerationMin = 0.00,
    radialAccelerationMax = 0.00,

    -- Size
    startSizeMin = 0.050,
    startSizeMax = 0.100,
    endSizeMin = 0.020,
    endSizeMax = 0.050,

    -- Start color
    colorMinR = 0.000, colorMaxR = 0.000,
    colorMinG = 0.000, colorMaxG = 0.000,
    colorMinB = 0.000, colorMaxB = 0.000,
    colorMinA = 0.349, colorMaxA = 1.000,

    -- End color
    endColorMinR = 0.304, endColorMaxR = 0.000,
    endColorMinG = 0.304, endColorMaxG = 0.000,
    endColorMinB = 0.304, endColorMaxB = 0.000,
    endColorMinA = 0.000, endColorMaxA = 0.000,

    -- Lifetime
    lifetimeMin = 0.40,
    lifetimeMax = 1.00,
    systemLifetime = 0.02,

    -- Rotation
    rotationMinX = 0.00, rotationMaxX = 0.00,
    rotationMinY = 0.00, rotationMaxY = 0.00,
    rotationMinZ = 0.00, rotationMaxZ = 6.28,
    rotVelocityMinX = 0.00, rotVelocityMaxX = 0.00,
    rotVelocityMinY = 0.00, rotVelocityMaxY = 0.00,
    rotVelocityMinZ = -1.00, rotVelocityMaxZ = 1.00,

    -- Textures (stored as names for editor)
    textureNames = {"res/fx/sponge2.png"}
}

return particleConfig
