-- Particle System Configuration
-- Generated by Particle System Editor

local particleConfig = {
    maxParticles = 100,
    emissionRate = 200.0,
    blendMode = 1,  -- Alpha

    -- Point emitter (no polygon)
    emissionVertices = {0.0, 0.0},
    emissionVertexCount = 0,

    -- Velocity
    velocityMinX = -0.24,
    velocityMaxX = 0.24,
    velocityMinY = 0.20,
    velocityMaxY = 0.60,

    radialVelocityMin = 0.00,
    radialVelocityMax = 0.00,

    -- Acceleration
    accelerationMinX = 0.00,
    accelerationMaxX = 0.00,
    accelerationMinY = -1.00,
    accelerationMaxY = -0.50,

    radialAccelerationMin = 0.00,
    radialAccelerationMax = 0.00,

    -- Size
    startSizeMin = 0.050,
    startSizeMax = 0.100,
    endSizeMin = 0.001,
    endSizeMax = 0.001,

    -- Start color
    colorMinR = 0.000, colorMaxR = 0.000,
    colorMinG = 0.953, colorMaxG = 0.212,
    colorMinB = 1.000, colorMaxB = 1.000,
    colorMinA = 1.000, colorMaxA = 1.000,

    -- End color
    endColorMinR = 0.000, endColorMaxR = 0.000,
    endColorMinG = 0.918, endColorMaxG = 0.024,
    endColorMinB = 1.000, endColorMaxB = 1.000,
    endColorMinA = 1.000, endColorMaxA = 1.000,

    -- Lifetime
    lifetimeMin = 0.43,
    lifetimeMax = 0.68,
    systemLifetime = 0.05,

    -- Rotation
    rotateWithVelocity = true,
    rotationMinX = 0.00, rotationMaxX = 0.00,
    rotationMinY = 0.00, rotationMaxY = 0.00,
    rotationMinZ = 0.00, rotationMaxZ = 6.28,
    rotVelocityMinX = 0.00, rotVelocityMaxX = 0.00,
    rotVelocityMinY = 0.00, rotVelocityMaxY = 0.00,
    rotVelocityMinZ = -1.00, rotVelocityMaxZ = 1.00,

    -- Textures (stored as names for editor)
    textureNames = {"res/fx/drop.png"}
}

return particleConfig
