-- Particle System Configuration
-- Generated by Particle System Editor

local particleConfig = {
    maxParticles = 10000,
    emissionRate = 1000.0,
    blendMode = 0,  -- Additive

    -- Point emitter (no polygon)
    emissionVertices = {0.0, 0.0},
    emissionVertexCount = 0,

    -- Velocity
    velocityMinX = -0.05,
    velocityMaxX = 0.05,
    velocityMinY = 0.05,
    velocityMaxY = 0.15,

    radialVelocityMin = 0.00,
    radialVelocityMax = 0.00,

    -- Acceleration
    accelerationMinX = 0.00,
    accelerationMaxX = 0.00,
    accelerationMinY = -0.01,
    accelerationMaxY = -0.05,

    radialAccelerationMin = 0.00,
    radialAccelerationMax = 0.00,

    -- Size
    startSizeMin = 0.050,
    startSizeMax = 0.100,
    endSizeMin = 0.020,
    endSizeMax = 0.050,

    -- Start color
    colorMinR = 1.000, colorMaxR = 1.000,
    colorMinG = 1.000, colorMaxG = 1.000,
    colorMinB = 1.000, colorMaxB = 1.000,
    colorMinA = 1.000, colorMaxA = 1.000,

    -- End color
    endColorMinR = 1.000, endColorMaxR = 1.000,
    endColorMinG = 0.000, endColorMaxG = 0.200,
    endColorMinB = 0.000, endColorMaxB = 0.000,
    endColorMinA = 0.000, endColorMaxA = 0.000,

    -- Lifetime
    lifetimeMin = 10.00,
    lifetimeMax = 10.00,

    -- Rotation
    rotationMinX = 0.00, rotationMaxX = 0.00,
    rotationMinY = 0.00, rotationMaxY = 0.00,
    rotationMinZ = 0.00, rotationMaxZ = 6.28,
    rotVelocityMinX = 0.00, rotVelocityMaxX = 0.00,
    rotVelocityMinY = 0.00, rotVelocityMaxY = 0.00,
    rotVelocityMinZ = -1.00, rotVelocityMaxZ = 1.00,

    -- Textures (stored as names for editor)
    textureNames = {"res/fx/bloom.png", "res/fx/sparkle1.png"}
}

return particleConfig
