set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(MINGW_PREFIX x86_64-w64-mingw32)

find_program(CMAKE_C_COMPILER NAMES ${MINGW_PREFIX}-gcc REQUIRED)
find_program(CMAKE_CXX_COMPILER NAMES ${MINGW_PREFIX}-g++ REQUIRED)
find_program(CMAKE_RC_COMPILER NAMES ${MINGW_PREFIX}-windres)
find_program(CMAKE_STRIP NAMES ${MINGW_PREFIX}-strip)

# Allow callers to specify a sysroot for installed Windows libraries via -DMINGW64_SYSROOT=...
# or via the MINGW64_SYSROOT environment variable.
if(NOT DEFINED MINGW64_SYSROOT AND DEFINED ENV{MINGW64_SYSROOT})
    set(MINGW64_SYSROOT "$ENV{MINGW64_SYSROOT}" CACHE PATH "MinGW64 sysroot directory")
endif()
if(DEFINED MINGW64_SYSROOT)
    list(APPEND CMAKE_FIND_ROOT_PATH "${MINGW64_SYSROOT}")
endif()
list(APPEND CMAKE_FIND_ROOT_PATH /usr/${MINGW_PREFIX})

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
